package planner

// Contract represents a shared interface or type definition that spans multiple tasks.
type Contract struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	FilePath    string `json:"file_path"`
}

// ProposedTask is a task generated by the LLM task splitter.
type ProposedTask struct {
	Title             string     `json:"title"`
	Description       string     `json:"description"`
	ModulePath        string     `json:"module_path"`
	DependsOn         []string   `json:"depends_on"`
	ReadOnlyPaths     []string   `json:"read_only_paths"`
	ForbiddenPaths    []string   `json:"forbidden_paths"`
	IntegrationPoints []string   `json:"integration_points"`
	ProvidedContracts []Contract `json:"provided_contracts"`
	ConsumedContracts []string   `json:"consumed_contracts"`
}

// Provider is the interface for LLM-powered task splitting.
type Provider interface {
	// SplitDesign decomposes a PM design document into agent-assignable tasks.
	// projectConfig can contain provider-specific settings (model, temperature, etc.)
	SplitDesign(design string, projectConfig map[string]any) ([]ProposedTask, error)
}

// ContractGenerator is an optional interface for providers that support
// generating shared interface/type contracts across tasks.
// It is intentionally separate from Provider to avoid breaking existing implementations.
type ContractGenerator interface {
	GenerateContracts(tasks []ProposedTask, projectConfig map[string]any) ([]Contract, error)
}
